name:                haskell-parser
version:             0.1.0.0

extra-source-files:
- README.md

description:         haskell-parser

ghc-options:
- -Wall
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-unused-top-binds
- -Wno-unused-local-binds
- -Wno-unused-pattern-binds
- -Wno-unused-matches
- -Wno-missing-signatures
- -Wno-type-defaults
- -Wno-compat-unqualified-imports
- -Wno-name-shadowing
- -fdefer-typed-holes

language: GHC2021

default-extensions:
- InstanceSigs
- NamedFieldPuns

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-parser
    when:
    - condition: false
      other-modules: Paths_haskell-parser

tests:
  haskell-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-parser
    - hspec
    - hspec-discover
    - QuickCheck

